/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/FloatContainer copy.vue')['default']
    FloatContainer: typeof import('./src/components/FloatContainer.vue')['default']
    FloatProxy: typeof import('./src/components/FloatProxy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
